export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const FORGET_PASSWORD ='FORGET_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const NO_REPOS = 'NO_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SET_PRIVACYOPTIONS = 'SET_PRIVACYOPTIONS'
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const GET_FRIEND = 'GET_FRIEND';
export const GET_FRIENDSLIST = 'GET_FRIENDSLIST';
export const GET_FRIENDREQUESTSLIST = 'GET_FRIENDREQUESTSLIST';
export const SEND_FRIENDREQUEST = 'SEND_FRIENDREQUEST';
export const ACCEPT_FRIENDREQUEST = 'ACCEPT_FRIENDREQUEST';
export const REJECT_FRIENDREQUEST = 'REJECT_FRIENDREQUEST';
export const UNFRIEND = 'UNFRIEND';
export const CANCEL_REQUEST = 'CANCEL_REQUEST';
export const FRIENDS_ERROR = 'FRIENDS_ERROR';

// Messages feature action types
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const GET_MESSAGES = 'GET_MESSAGES';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const GET_USERS = 'GET_USERS';
export const DELETE_ALL_MESSAGES = 'DELETE_ALL_MESSAGES';
export const CONNECTED_USERS = 'CONNECTED_USERS';

//Group feature action types
export const GET_GROUPS = 'GET_GROUPS';
export const ADD_GROUP = 'ADD_GROUP';
export const GET_GROUP = 'GET_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const GET_GROUPPOST = 'GET_GROUPPOST';
export const ADD_GROUPPOST = 'ADD_GROUPPOST';
export const UPDATE_GROUPPOST = 'UPDATE_GROUPPOST';
export const DELETE_GROUPPOST = 'DELETE_GROUPPOST';
export const ADD_POSTCOMMENT = 'ADD_POSTCOMMENT';
export const DELETE_POSTCOMMENT = 'DELETE_POSTCOMMENT';
export const JOIN_GROUP = 'JOIN_GROUP';
export const LEAVE_GROUP = 'LEAVE_GROUP';

export const ADD_EVENT = 'ADD_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';

//Emoji action types
export const ADD_EMOJI = 'ADD_EMOJI';
export const REMOVE_EMOJI = 'REMOVE_EMOJI';
export const ADD_GROUPPOSTEMOJI = 'ADD_GROUPPOSTEMOJI';
export const REMOVE_GROUPPOSTEMOJI = 'REMOVE_GROUPPOSTEMOJI';

// Notifications action type
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const DELETE_NOTIFICATIONS = 'DELETE_NOTIFICATIONS';
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR';
